import * as T from 'three/webgpu';
import {random,capsuleBetween} from './math.js';
import {sites} from './simulation.js';
const rng=random();
export function height(x,z){const surface=T.MathUtils.smoothstep(x,4,13)*T.MathUtils.smoothstep(-z,19,30);return Math.sin(x*1.3+z*.7)*.035+Math.sin(z*2.5-x)*.022+surface*3.5;}
function segmentDistance(x,z,a,b){const dx=b.x-a.x,dz=b.z-a.z,t=T.MathUtils.clamp(((x-a.x)*dx+(z-a.z)*dz)/(dx*dx+dz*dz),0,1);return Math.hypot(x-a.x-t*dx,z-a.z-t*dz);}
const paths=[['home','store',2.6],['store','dig',2.5],['store','surface',2.9],['dig','spoil',2.6]];
export function field(x,z){let d=Infinity;for(const [name,radius]of [['home',6],['store',6],['dig',5],['surface',9],['spoil',3]])d=Math.min(d,Math.hypot(x-sites[name].x,z-sites[name].z)-radius);for(const [a,b,r]of paths)d=Math.min(d,segmentDistance(x,z,sites[a],sites[b])-r);return d;}
export function walkable(x,z){return field(x,z)<-.45;}
function soilTexture(){const c=document.createElement('canvas');c.width=c.height=512;const ctx=c.getContext('2d');ctx.fillStyle='#776047';ctx.fillRect(0,0,512,512);for(let i=0;i<65000;i++){const v=Math.floor(35+rng()*100);ctx.fillStyle=`rgba(${v+22},${v+5},${v-14},${.2+rng()*.5})`;const r=rng()*2.2;ctx.beginPath();ctx.ellipse(rng()*512,rng()*512,r*1.8,r,rng()*6,0,Math.PI*2);ctx.fill();}const texture=new T.CanvasTexture(c);texture.wrapS=texture.wrapT=T.RepeatWrapping;texture.repeat.set(13,13);texture.colorSpace=T.SRGBColorSpace;return texture;}
export function buildWorld(scene,state){
 const texture=soilTexture();const soil=new T.MeshStandardMaterial({color:0xb79b71,map:texture,bumpMap:texture,bumpScale:.13,roughness:.97});const darkSoil=new T.MeshStandardMaterial({color:0x57422e,map:texture,bumpMap:texture,bumpScale:.09,roughness:.93});const rockMat=new T.MeshStandardMaterial({color:0x6e6651,roughness:.84,map:texture,bumpMap:texture,bumpScale:.12});
 const groundGeo=new T.PlaneGeometry(65,65,180,180);groundGeo.rotateX(-Math.PI/2);const p=groundGeo.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getZ(i)-17;p.setXYZ(i,x,height(x,z)-.055,z);}groundGeo.computeVertexNormals();const ground=new T.Mesh(groundGeo,soil);ground.receiveShadow=true;scene.add(ground);
 const matrix=new T.Object3D(),grainGeo=new T.IcosahedronGeometry(1,0);const grains=new T.InstancedMesh(grainGeo,soil,16000);let count=0;
 for(let i=0;i<23000&&count<16000;i++){const x=rng()*51-24,z=rng()*54-42;if(field(x,z)>1)continue;const size=.025+rng()**3*.19;matrix.position.set(x,height(x,z)+size*.25,z);matrix.rotation.set(rng()*6,rng()*6,rng()*6);matrix.scale.set(size*1.4,size*.65,size);matrix.updateMatrix();grains.setMatrixAt(count,matrix.matrix);grains.setColorAt(count,new T.Color().setHSL(.085+rng()*.045,.18+rng()*.22,.12+rng()*.22));count++;}grains.count=count;grains.receiveShadow=true;scene.add(grains);
 const walls=new T.InstancedMesh(new T.IcosahedronGeometry(1,2),darkSoil,14000);let wallCount=0;
 for(let x=-23;x<26;x+=.62)for(let z=-43;z<9;z+=.62){const f=field(x,z);if(f<-.18||f>1.25||x>5&&z<-23)continue;for(let j=0;j<5;j++){matrix.position.set(x+(rng()-.5)*.2,height(x,z)+j*.63+.15,z+(rng()-.5)*.2);matrix.scale.set(.48+rng()*.28,.43+rng()*.2,.48+rng()*.25);matrix.rotation.set(rng()*2,rng()*4,rng()*2);matrix.updateMatrix();walls.setMatrixAt(wallCount,matrix.matrix);walls.setColorAt(wallCount,new T.Color().setHSL(.07,.25,.16+rng()*.2));wallCount++;}}walls.count=wallCount;walls.castShadow=true;walls.receiveShadow=true;scene.add(walls);
 const bark=new T.MeshStandardMaterial({color:0x5d4227,roughness:.9,map:texture,bumpMap:texture,bumpScale:.22});
 const root=(points,r)=>{const curve=new T.CatmullRomCurve3(points.map(p=>new T.Vector3(...p)));const mesh=new T.Mesh(new T.TubeGeometry(curve,40,r,9,false),bark);mesh.castShadow=true;mesh.receiveShadow=true;scene.add(mesh);};
 root([[-6,1,-5],[-4,3.4,-6],[0,4.1,-7],[3,2.6,-7],[4,0,-8]],.45);root([[-5,3.5,-6],[-2,4.5,-9],[1,5,-16],[4,4,-22],[8,4,-27]],.58);root([[2,5,-15],[-2,4,-18],[-5,3.8,-24],[-8,1.8,-27],[-9,0,-28]],.34);
 for(let i=0;i<40;i++){const x=-4+rng()*8,z=-9-rng()*16;root([[x,3+rng(),z],[x+.3,2.5,z+.6],[x+.5,1.2+rng(),z+1.2]],.018+rng()*.035);}
 // Tunnel canopy is continuous geometry with a walkable open bottom.
 const archVertices=[],archIndices=[];for(let iz=0;iz<=36;iz++){const z=-6-iz/36*3.5;for(let ia=0;ia<=24;ia++){const a=ia/24*Math.PI;archVertices.push(Math.cos(a)*2.85,Math.sin(a)*3.15+height(0,z),z);}}for(let iz=0;iz<36;iz++)for(let ia=0;ia<24;ia++){const a=iz*25+ia,b=a+25;archIndices.push(a,a+1,b,b,a+1,b+1);}const archGeo=new T.BufferGeometry();archGeo.setAttribute('position',new T.Float32BufferAttribute(archVertices,3));archGeo.setIndex(archIndices);archGeo.computeVertexNormals();const archMat=darkSoil.clone();archMat.side=T.DoubleSide;const arch=new T.Mesh(archGeo,archMat);arch.receiveShadow=true;arch.castShadow=true;scene.add(arch);
 const leafMat=new T.MeshPhysicalMaterial({color:0x5e742b,roughness:.75,side:T.DoubleSide,transmission:.12,thickness:.06});
 function leaf(x,y,z,size,angle){const g=new T.BufferGeometry(),v=[],idx=[];for(let i=0;i<=18;i++){const t=i/18,w=Math.sin(Math.PI*t)*size*.29;v.push(-w,Math.sin(t*3)*size*.08,t*size,w,Math.sin(t*3)*size*.08,t*size);}for(let i=0;i<18;i++){const a=i*2;idx.push(a,a+1,a+2,a+1,a+3,a+2);}g.setAttribute('position',new T.Float32BufferAttribute(v,3));g.setIndex(idx);g.computeVertexNormals();const m=new T.Mesh(g,leafMat);m.position.set(x,y,z);m.rotation.y=angle;m.castShadow=true;m.receiveShadow=true;scene.add(m);const vein=capsuleBetween(new T.Vector3(x,y+.025,z),new T.Vector3(x+Math.sin(angle)*size,y+.04,z+Math.cos(angle)*size),.017,new T.MeshStandardMaterial({color:0x9caa4c,roughness:.7}));scene.add(vein);return m;}
 leaf(-2,.03,1,3.1,-.65);leaf(-1,.08,1.5,2.5,-.3);leaf(1,.05,-14,2.7,.6);
 // Surface vegetation uses curved, tapered blades with physical translucency.
 for(let i=0;i<95;i++){const x=5+rng()*17,z=-24-rng()*14;if(Math.hypot(x-13,z+31)>9)continue;const y=height(x,z);const h=3+rng()*8;const g=new T.BufferGeometry(),v=[],idx=[];const bend=rng()*2-1;for(let j=0;j<=12;j++){const t=j/12,w=(1-t)*(.12+rng()*.1);v.push(-w+bend*t*t,t*h,t*t*2,w+bend*t*t,t*h,t*t*2);}for(let j=0;j<12;j++){const a=j*2;idx.push(a,a+1,a+2,a+1,a+3,a+2);}g.setAttribute('position',new T.Float32BufferAttribute(v,3));g.setIndex(idx);g.computeVertexNormals();const m=new T.Mesh(g,leafMat);m.position.set(x,y,z);m.rotation.y=rng()*6.28;m.castShadow=true;scene.add(m);}
 const moss=new T.InstancedMesh(new T.ConeGeometry(.07,.45,4),new T.MeshStandardMaterial({color:0x617b31,roughness:.9}),2500);for(let i=0;i<2500;i++){const a=rng()*6.28,r=3+rng()*6,x=13+Math.cos(a)*r,z=-31+Math.sin(a)*r;matrix.position.set(x,height(x,z)+.12,z);matrix.rotation.set(rng()*.4,rng()*6,rng()*.4);matrix.scale.setScalar(.5+rng());matrix.updateMatrix();moss.setMatrixAt(i,matrix.matrix);moss.setColorAt(i,new T.Color().setHSL(.19+rng()*.07,.45,.13+rng()*.13));}scene.add(moss);
 for(let i=0;i<34;i++){const x=6+rng()*15,z=-25-rng()*13;const r=.3+rng()*.9;const mesh=new T.Mesh(new T.IcosahedronGeometry(r,2),rockMat);mesh.position.set(x,height(x,z)+r*.3,z);mesh.scale.set(1.2,.7,1);mesh.castShadow=true;mesh.receiveShadow=true;scene.add(mesh);}
 const water=new T.Mesh(new T.SphereGeometry(1,32,20),new T.MeshPhysicalMaterial({color:0xcadbb8,roughness:.035,metalness:.05,transmission:.85,thickness:.5,ior:1.333,transparent:true,opacity:.85}));water.position.set(15,height(15,-29)+.3,-29);water.scale.set(1.8,.65,1.5);scene.add(water);
 const glass=new T.Mesh(new T.PlaneGeometry(58,24),new T.MeshPhysicalMaterial({color:0xbcccb1,transparent:true,opacity:.10,roughness:.18,metalness:.25,side:T.DoubleSide}));glass.position.set(0,10,-42);scene.add(glass);
 const seedMat=new T.MeshStandardMaterial({color:0xb49a55,roughness:.66});const seedGeo=new T.SphereGeometry(.22,12,8);for(let i=0;i<45;i++){const a=rng()*6,r=rng()*1.5;const m=new T.Mesh(seedGeo,seedMat);m.position.set(Math.cos(a)*r,height(0,-14)+.13+Math.floor(i/15)*.15,-14+Math.sin(a)*r);m.scale.set(1,.7,1.9);m.rotation.y=rng()*6;m.castShadow=true;scene.add(m);}
 if(!state.items.some(i=>i.kind==='seed'))for(let i=0;i<9;i++)state.items.push({id:state.nextItem++,kind:'seed',x:10+rng()*5,z:-28-rng()*5,y:0,deposited:false});
 const trail=new T.Group();scene.add(trail);const scentMat=new T.MeshBasicMaterial({color:0xd2ad63,transparent:true,opacity:.32});for(const [a,b]of paths){for(let t=0;t<1;t+=.033){const x=T.MathUtils.lerp(sites[a].x,sites[b].x,t),z=T.MathUtils.lerp(sites[a].z,sites[b].z,t);const m=new T.Mesh(new T.SphereGeometry(.035,5,4),scentMat);m.position.set(x,height(x,z)+.12,z);trail.add(m);}}
 const digCells=new Map();for(let ix=0;ix<7;ix++)for(let iy=0;iy<5;iy++)for(let iz=0;iz<3;iz++){const id=`${ix}:${iy}:${iz}`;if(state.removed.includes(id))continue;const x=-16.3+ix*.67,z=-28.5-iz*.6,y=iy*.58+.2;const m=new T.Mesh(new T.IcosahedronGeometry(.48,1),soil);m.position.set(x,y,z);m.rotation.set(rng(),rng(),rng());m.scale.set(1,.85,1);m.castShadow=true;m.receiveShadow=true;m.userData.cell=id;scene.add(m);digCells.set(id,m);}
 const spoilRing=new T.Mesh(new T.TorusGeometry(1.5,.045,6,45),new T.MeshStandardMaterial({color:0xa7965c,roughness:1}));spoilRing.rotation.x=Math.PI/2;spoilRing.position.set(-8,.08,-19);scene.add(spoilRing);
 const motesGeo=new T.BufferGeometry(),motes=[];for(let i=0;i<500;i++)motes.push(rng()*40-18,rng()*6+.2,-rng()*40);motesGeo.setAttribute('position',new T.Float32BufferAttribute(motes,3));const dust=new T.Points(motesGeo,new T.PointsMaterial({color:0xd4c3a0,size:.023,transparent:true,opacity:.4}));scene.add(dust);
 return {digCells,soil,seedMat,seedGeo,trail,dust};
}
